### PR TITLE
added truncate function

### PR DESCRIPTION
**Pull request by kidata**
since Freemarker unfortunately offers no truncate function out of the box, i have this useful suggestion

### CODE REVIEW

**Comment by lpireyn** [comment]
Thanks @kidata, but I fail to see the use of this function. How is it different from just a `?substring`?

**Comment by kidata** [comment]
If you use `value?substring(0, 254)` to limit a string to a max length of 255 chars, `?substring` fails if the length of value is smaller then 255. Therefore the `?right_pad` hack.

**Comment by lpireyn** [comment]
A simple test of the length would be more efficient and readable. Also, the `trim` builtin trims leading spaces as well as trailing spaces, so you may end up with an empty string.

**Comment by kidata** [comment]
OK, you're right. I'll fix that.

**Pull request merged**
